scan_matcher:
  ros__parameters:
    input_cloud_topic: "/multiBeam"
    output_cloud_topic: "/modified_cloud"
    global_frame_id: "map"
    registration_method: "NDT"
    ndt_resolution: 2.0
    ndt_num_threads: 2
    gicp_corr_dist_threshold: 5.0
    trans_for_map_update: 0.5
    rotation_for_map_update: 0.2
    vg_size_for_input: 0.1
    vg_size_for_map: 0.1
    use_min_max_filter: false
    scan_min_range: 10.0
    scan_max_range: 120.0
    scan_period: 0.2
    map_publish_period: 1.0
    num_targeted_cloud: 20
    debug: true
    debug_cloud_topic: "/target_cloud"